version: '3.8'

services:
  db:
    image: postgres:14.1
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  api:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
